# Generated by Django 6.0.4 on 2026-04-20 15:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_annonce', models.CharField(editable=False, max_length=10, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('terrain', 'Terrain'), ('maison', 'Maison'), ('appartement', 'Appartement'), ('commercial', 'Commercial'), ('Lotissement', 'Lotissement'), ('Amenagement', 'Aménagement'), ('Financement', 'Financement')], max_length=20)),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('prix', models.CharField(max_length=50)),
                ('surface', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('img_principale', models.ImageField(blank=True, null=True, upload_to='annonces/images/')),
                ('note', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_publie', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=100)),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('texte', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='annonces.annonce')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DemandeContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='annonces.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='annonces/documents/')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='annonces.annonce')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/images/')),
                ('ordre', models.IntegerField(default=0)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
