# Generated by Django 6.0.4 on 2026-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='type',
            field=models.CharField(choices=[('terrain', 'Terrain'), ('Location de Terres', 'Location de Terres'), ('Bail Emphytéotique', 'Bail Emphytéotique'), ('Partenariat Agricole', 'Partenariat Agricole'), ('Recherche de Financement', 'Recherche de Financement'), ('Amenagement', 'Aménagement')], max_length=30),
        ),
    ]
