# Generated by Django 6.0 on 2026-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_alter_annonce_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='annonces/videos/'),
        ),
    ]
